# pull official base image
FROM node:21-bullseye

# set working directory
WORKDIR /amper_steffi_ui_garden_build_checks/

# install app dependencies
COPY package*.json .
RUN npm ci
RUN npx playwright install --with-deps chromium
COPY . .

# start app
CMD ["npm","run","ci:test"]